service:
  name: linkbit-backend

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handlers.hello
    events:
      - http:
          method: get
          path: hello
