service:
  name: linkbit-backend

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-2

functions:
  getApplicant:
    handler: handlers.getApplicant
    events:
      - http:
          method: get
          path: applicant
          cors: true
  getApplicants:
    handler: handlers.getApplicants
    events:
      - http:
          method: get
          path: applicants
          cors: true
  getSponser:
    handler: handlers.getSponser
    events:
      - http:
          method: get
          path: sponser
          cors: true
  getSponsers:
    handler: handlers.getSponsers
    events:
      - http:
          method: get
          path: sponsers
          cors: true
  getAddress:
    handler: handlers.getLinkAddress
    events:
      - http:
          method: get
          path: address
          cors: true
  createAddress:
    handler: handlers.createAddress
    events:
      - http:
          method: post
          path: address
          cors: true
  linkAddress:
    handler: handlers.linkAddress
    events:
      - http:
          method: put
          path: address
          cors: true
  getCertText:
    handler: handlers.getCertText
    events:
      - http:
          method: get
          path: cert
          cors: true
 
